from pathlib import Path

import pandas as pd
import streamlit as st


SEGMENT_ORDER = ["low", "medium", "high", "critical"]

SEGMENT_ACTIONS = {
    "low": "Standard automatic processing",
    "medium": "Light monitoring",
    "high": "Priority review",
    "critical": "Manual review and early-warning alert",
}


RISK_SEGMENT_SUMMARY_PATH = Path("reports/early_risk_segment_summary.csv")
RISK_SCORES_PATH = Path("reports/early_risk_scores.csv")


st.set_page_config(
    page_title="LoanOps Risk Dashboard",
    page_icon="🏦",
    layout="wide",
)


@st.cache_data
def load_risk_segment_summary(path: Path) -> pd.DataFrame:
    data = pd.read_csv(path)

    if "risk_segment" not in data.columns:
        first_column = data.columns[0]
        data = data.rename(columns={first_column: "risk_segment"})

    data["risk_segment"] = pd.Categorical(
        data["risk_segment"],
        categories=SEGMENT_ORDER,
        ordered=True,
    )

    return data.sort_values("risk_segment").reset_index(drop=True)


@st.cache_data
def load_risk_scores(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)


def format_percentage(value: float) -> str:
    return f"{value:.1%}"


def main() -> None:
    st.title("LoanOps Risk Dashboard")

    st.markdown(
        """
        This dashboard presents the operational delay risk segmentation results
        generated by the LoanOps early-warning model.

        The goal is to transform model probabilities into actionable business
        groups that can help banking operations teams prioritize monitoring and
        manual review.
        """
    )

    if not RISK_SEGMENT_SUMMARY_PATH.exists():
        st.error(
            "Risk segment summary file not found. "
            "Expected file: reports/early_risk_segment_summary.csv"
        )
        return

    risk_segment_summary = load_risk_segment_summary(
        RISK_SEGMENT_SUMMARY_PATH
    )

    st.subheader("Risk Segmentation Overview")

    total_cases = int(risk_segment_summary["cases"].sum())
    average_delay_rate = (
        risk_segment_summary["actual_delay_rate"]
        .mul(risk_segment_summary["cases"])
        .sum()
        / total_cases
    )

    critical_row = risk_segment_summary[
        risk_segment_summary["risk_segment"].astype(str) == "critical"
    ]

    if not critical_row.empty:
        critical_delay_rate = float(critical_row["actual_delay_rate"].iloc[0])
        critical_cases = int(critical_row["cases"].iloc[0])
    else:
        critical_delay_rate = 0.0
        critical_cases = 0

    col1, col2, col3 = st.columns(3)

    col1.metric(
        label="Total cases",
        value=f"{total_cases:,}",
    )

    col2.metric(
        label="Average delay rate",
        value=format_percentage(average_delay_rate),
    )

    col3.metric(
        label="Critical segment delay rate",
        value=format_percentage(critical_delay_rate),
        delta=f"{critical_cases:,} cases",
    )

    st.subheader("Actual Delay Rate by Risk Segment")

    chart_data = risk_segment_summary.set_index("risk_segment")[
        ["actual_delay_rate"]
    ]

    st.bar_chart(chart_data)

    st.subheader("Segment Summary")

    display_summary = risk_segment_summary.copy()

    percentage_columns = [
        "avg_delay_probability",
        "actual_delay_rate",
        "min_probability",
        "max_probability",
        "delay_rate_lift_vs_average",
        "delayed_case_share",
    ]

    for column in percentage_columns:
        if column in display_summary.columns:
            if column == "delay_rate_lift_vs_average":
                display_summary[column] = display_summary[column].map(
                    lambda value: f"{value:.2f}x"
                )
            else:
                display_summary[column] = display_summary[column].map(
                    format_percentage
                )

    if "risk_segment" in display_summary.columns:
        display_summary["recommended_action"] = (
            display_summary["risk_segment"]
            .astype(str)
            .map(SEGMENT_ACTIONS)
        )

    st.dataframe(
        display_summary,
        use_container_width=True,
        hide_index=True,
    )

    st.subheader("Business Interpretation")

    st.markdown(
        """
        The dashboard shows whether the model ranking is operationally useful.
        A good early-warning model should show increasing observed delay rates
        from low to critical risk.

        In this project, the risk segmentation layer makes the model output
        easier to use by translating probabilities into business actions:

        - Low: standard automatic processing.
        - Medium: light monitoring.
        - High: priority review.
        - Critical: manual review and early-warning alert.
        """
    )

    if RISK_SCORES_PATH.exists():
        st.subheader("Case-Level Risk Scores")

        risk_scores = load_risk_scores(RISK_SCORES_PATH)

        selected_segment = st.selectbox(
            "Filter by risk segment",
            options=["all", *SEGMENT_ORDER],
        )

        filtered_scores = risk_scores.copy()

        if selected_segment != "all" and "risk_segment" in filtered_scores.columns:
            filtered_scores = filtered_scores[
                filtered_scores["risk_segment"] == selected_segment
            ]

        st.dataframe(
            filtered_scores.head(500),
            use_container_width=True,
            hide_index=True,
        )

        st.caption(
            "Showing up to 500 rows for readability."
        )
    else:
        st.info(
            "Case-level risk scores file not found. "
            "Expected file: reports/early_risk_scores.csv"
        )


if __name__ == "__main__":
    main()